<?php
/** @package Aviacao::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("AeronaveMap.php");

/**
 * AeronaveDAO provides object-oriented access to the aeronave table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Aviacao::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class AeronaveDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var int */
	public $IdCliente;

	/** @var char */
	public $Matricula;

	/** @var char */
	public $Modelo;

	/** @var year */
	public $Ano;

	/** @var char */
	public $Cor;


	/**
	 * Returns the foreign object based on the value of IdCliente
	 * @return Cliente
	 */
	public function GetIdCliente()
	{
		return $this->_phreezer->GetManyToOne($this, "aeronave_ibfk_1");
	}


}
?>